#training
epochs: 1000
lr: 0.01
weight_decay: 0
drop_prob: 0.7

# network
accum: add
hidden_size: 
  - 500
  - 75
num_basis: 2
rgc_bn: True
rgc_relu: True
dense_bn: True
dense_relu: True
bidec_drop: False
num_features: 3

# dataset
#root: data/netflix
root: data/book

# comet-ml (optional)
workspace: 
project_name: 
api_key: 

# environment
gpu_id: 0 # -1 mean cpu
